import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Box, Flex, Grid, GridItem, Spacer} from "@chakra-ui/react"
import avatar from '../public/renlu.png'
import {BiBody, BiBookOpen, BiPhone, BiBriefcase, BiCurrentLocation, BiMailSend, BiCode} from "react-icons/bi";
import Link from "next/link";
import Header from "../components/header";
import {useEffect, useState} from "react";




export default function Page(props:any) {
    const profile = props.profile;
    const employments = props.employmentHistory.map((item:any)=>{
        return <li key={item.employer} className={"mb-2"}>
            <h3 style={{fontSize:"18px",fontWeight:"bolder"}}>
                {item.jobTitle} at {item.employer} ,{item.city}
            </h3>
            <p className={"text-gray-400 p-1"}>
                {item.startDate}-{item.endDate}
            </p>
            <p className={"m6-2"} style={{whiteSpace: 'pre-wrap'}}>
                {item.description}
            </p>
        </li>
    })
    const educationItems = props.education.map( (item:any)=>{
        return <li key={item.school}>
            <h3 style={{fontSize:"18px",fontWeight:"bolder"}}>
                {item.degree},{item.school} , {item.city}
            </h3>
            <p className={"text-gray-400 p-1"}>
                {item.startDate}-{item.endDate}
            </p>
            <p className={"mt-2"} style={{whiteSpace: 'pre-wrap'}}>
                {item.description}
            </p>
        </li>
    })
    const links = props.links.map((item:any)=>{
        return <li key={item.label}>
            <Link target="_blank" href={item.href}>{item.label}</Link>
        </li>
    })
    const projects = props.projects.map((item:any)=>{
        return <li key={item.subject} className={"mb-2"}>
            <h3 style={{fontSize:"16px",fontWeight:"bolder"}}><a href={item.link} rel="noreferrer" target={"_blank"}>{item.subject}</a> </h3>
            <p style={{whiteSpace: 'pre-wrap'}} >
                {item.desc}
            </p>
        </li>

    })
    const skills = props.skills.map((item:any)=>{
        return <li key={item.skill}>
            {item.skill}
        </li>
    });
    const [leftSize,setLeft] = useState(6)
    const [rightSize,setRight] = useState(2)
    function  handleResize(){
        if(window.outerWidth<850){
            setLeft(8)
            setRight(8)
        }else{
            setLeft(6)
            setRight(2)
        }
    }
    useEffect(()=>{
        console.log(window.outerWidth)
        if(window.outerWidth<850){
           setLeft(8)
           setRight(8)
        }
        window.addEventListener('resize', handleResize);
    },[])

    return <div className={styles.container}>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main} >
                <Header/>
                <div id={"main-area"}>
                    <div style={{height: "120px"}} className={"p-8"} >
                        <Flex>
                            <Box w='120px' h='120' >
                                <Image src={avatar} className={"rounded-lg"} alt={"avatar"} width={120} height={120}/>
                            </Box>

                            <Box w='400px' h='10' className={"pl-2"}>
                                <h1>{profile.firstName}{props.lastName} </h1>
                                objective: {profile.wantedJobTitle} <br/>
                                location:{profile.city},{profile.country} <br/>
                            </Box>

                        </Flex>

                    </div>

                    <Grid templateColumns={'repeat(8,1fr)'} className={"mt-2"}>
                        <GridItem colSpan={leftSize}>
                            <div className={"p-8 mt-2 mb-1"}>
                                <h2>
                                    <BiBody width={8} style={{float: "left", marginRight: "6px"}}/>
                                    Profile
                                </h2>
                                <div style={{whiteSpace: 'pre-wrap'}} >
                                    {props.professionalSummary}
                                </div>

                            </div>

                            <div className="p-8 m-1">
                                <h2>
                                    <BiBookOpen width={8} style={{float: "left", marginRight: "6px"}}/>
                                    Education
                                </h2>
                                <ul>
                                    {educationItems}
                                </ul>
                            </div>

                            <div className="p-8 m-1">
                                <h2>
                                    <BiBriefcase width={8} style={{float: "left", marginRight: "6px"}}/>
                                    Employement History
                                </h2>
                                <ul>
                                    {employments}
                                </ul>
                            </div>

                            <div className="p-8 m-1">
                                <h2>
                                    <BiCode width={8} style={{float: "left", marginRight: "6px"}}/>
                                   Side projects
                                </h2>
                                <ul>
                                    {projects}
                                </ul>
                            </div>

                        </GridItem>
                        <GridItem colSpan={rightSize}>
                            <div className={"p-8 m6-2 "}>
                                <h2 className={"mt-2"}>
                                    Details
                                </h2>
                                <p>
                                    <BiCurrentLocation width={12} style={{float:"left"}} className={"mr-2"}/>
                                    {profile.city},{profile.country}
                                </p>
                                <p>
                                    <BiPhone width={12} style={{float:"left"}} className={"mr-2"}/>
                                    <a href={`tel:${profile.phone}`}>{profile.phone}</a>
                                </p>

                                <p>
                                    <BiMailSend width={12} style={{float:"left"}} className={"mr-2"}/>
                                    <a href={"mailto:"+profile.email}>{profile.email}</a>
                                </p>

                                <h2 className={"mb-2 mt-2"}>Links</h2>
                                <ul>
                                    {links}
                                </ul>
                            </div>
                        </GridItem>
                    </Grid>

                </div>


            </main>

            <style jsx>
                {`
            h1 {
            font-size:32px;
            font-weight:800;
            }
            h2 {
            font-size:24px;
            font-weight:600;
            }
            h3 a {
            font-size:20px;
            font-weight:400;
            text-decoration:underline;
            }
         
            `}
            </style>
        </div>

}


