export default
{
    en:
        {
            profile:{
                wantedJobTitle:"FullStack",
                firstName:"renlu",
                lastName:"",
                email:"hi@some-domain.com",
                phone:"180000000",
                country:"China",
                city:"Hangzhou",
                avatar:"",
                dateOfBirth:"Aug,1983"
            },
            professionalSummary:`I have over 17 years of programming experience in C, PHP, Java, Ruby, Python, Golang, TypeScript and many other languages.
Since 2016, I have been a technical manager and have experience leading a team of 60 people in various positions including server-side and front-end development, QA, client-side R&D, product design, etc.
I am an introvert, a good listener and easy to empathize with. Can also stay focused for a long time.
I maintain a strong interest in technology and in the last 4 years I have learned charming technologies such as golang, typescript, nextjs, etc.`,
            links:[
                {
                    label:"github",
                    href:"https://github.com/"
                },
            
                {
                    label:"ip4.dev",
                    href:"https://ip4.dev/"
                }
            ],
            skills:[
                {
                    skill:"public speaking",
                    score:5
                },{
                    skill:"event planning",
                    score:5
                },
                {
                    skill:"active listening",
                    score:5
                }
            ],
            projects:[
                {
                    subject:"unhtml.com",
                    desc:"Little tool to generate snapshots for code snippets.\ntech stack:html2canvas,typescript.",
                    link:"https://unhtml.com/"
                },
                {
                    subject: "https://ip4.dev",
                    desc:"Http api service provide geo information of specific IP.\ngeo data from maxmind.I provide golang-wrapper of c sdk from maxmind.web UI was based on vue3.\ngolang source code:https://github.com/gotapi/gmm",
                    link:"https://ip4.dev/"
                }
            ],
            education:[
                {
                    school:"Huazhong University of Science and Technology",
                    degree:"Bachelors",
                    startDate:"Sep,2001",
                    endDate:"June,2005",
                    city:"Wuhan",
                    description:""
                }
            ],
            employmentHistory:[
                {
                    jobTitle:"R&D",
                    employer:"Yahoo! China",
                    startDate:"Aug,2007",
                    endDate:"Jul,2011",
                    city:"Beijing",
                    description:"Responsible for the backend development of ks.cn.yahoo.com and yahoo music in the category of "
                },
                {
                    jobTitle:"R&D expert",
                    employer:"Alibaba Group",
                    startDate:"Apr,2013",
                    endDate:"June,2016",
                    city:"Hangzhou",
                    description:`1.(generated by chatGPT) as a member of the team that developed the first version of the Taobao app, I was responsible for the development of the Taobao app's server-side and client-side.`

                },
                {
                    jobTitle:"CTO",
                    employer:"some-site.cn",
                    startDate:"July,2016",
                    endDate:"Dec,2017",
                    city:"Beijing",
                    description:`glz.cn is a website that provides home renovation services. I was mainly responsible for the recruitment and performance evaluation of the technical R&D team in the early stage. In the later stage, I also lead the content operation and advertising team.
            `
                },
                {
                    jobTitle:"R&D Manager",
                    employer:"Shanghai not-exists Ltd",
                    startDate:"Nov,2020",
                    endDate:"-",
                    city:"Shanghai",
                    description:`1. Responsible for the recruitment and performance evaluation of the technical R&D team.
            `
                }
            ]
        },
    zh:{
        profile:{
            wantedJobTitle:"研发经理",
            firstName:"黄小滚",
            lastName:"",
            email:"hi@some-domain.com",
            phone:"18000000000",
            country:"中国",
            city:"杭州",
            avatar:"",
            dateOfBirth:"Aug,1983"
        },
        professionalSummary:`拥有17年的编程经验，包括C,PHP,Java,Ruby,Python，Golang,Typescript等不同的编程语言。
情绪稳定、善于倾听、共情能力强。也可以保持长时间的专注。
一直保持着对技术的强烈兴趣，近4年来学习了golang,typescript,nextjs等新兴的技术。
    `,
        links:[
            {
                label:"github",
                href:"https://github.com/"
            },
            {
                label:"ip4.dev",
                href:"https://ip4.dev/"
            }
        ],
        skills:[
            {
                skill:"公开演讲",
                score:5
            },{
                skill:"事务规划",
                score:5
            },
            {
                skill:"积极倾听",
                score:5
            }
        ],
        education:[
            {
                school:"华中科技大学",
                degree:"学士学位（统招本科)",
                startDate:"Sep,2001",
                endDate:"June,2005",
                city:"武汉",
                description:"在校期间，同时获得了材料科学、计算机科学两个专业的学位。"
            }
        ],
        employmentHistory:[
            {
                jobTitle:"PHP工程师",
                employer:"雅虎中国",
                startDate:"Aug,2007",
                endDate:"Jul,2011",
                city:"北京",
                description:"前期主要负责雅虎知识堂的服务端开发"
            },
            {
                jobTitle:"创始人",
                employer:"-",
                startDate:"Sep,2011",
                endDate:"Apr,2013",
                city:"北京",
                description:`离开雅虎织织了一个小的团队来为淘宝平台提供订单同步类工具。。。`
            },
            {
                jobTitle:"研发专家",
                employer:"Alibaba Group",
                startDate:"Apr,2013",
                endDate:"June,2016",
                city:"杭州",
                description:`1. 作为主搜索的PHP小组的PM，负责日常项目的上线排期 (主要是s.tao.com相关的变更)
2. 算法团队在工程端的bucket test的落地。`

            }
        ],
        projects:[
            {
                subject:"unhtml.com",
                desc:"一个基于nextjs的小工具，用以生成小段代码片段的截图。主要技术点有html2canvas,typescript",
                link:"https://unhtml.com/"
            },
            {
                subject: "https://ip4.dev",
                desc:"一个基于查询指定IP的地理信息的API。地理数据来自maxmind，用golang包装了maxmind的c library,提供了一个http的api。web界面使用vue3构建。golang版代码参见:https://github.com/gotapi/gmm",
                link:"https://ip4.dev/"
            },
            {
                subject: "kuafu",
                desc:"一个web服务器代理，类似nginx,主要提供了基于consul的后端机器动态寻址，和基于cookie的安全防护。",
                link:"https://github.com/gotapi/kuafu"
            }
        ]

    }
}
